services:
  web-nvtop:
    build: .
    container_name: web-nvtop
    ports:
      - "5464:80"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              driver: nvidia
    environment:
      NVIDIA_VISIBLE_DEVICES: all
